export type PropertyToolCategory =
  | 'before-buying'
  | 'hiring-budgeting'
  | 'remote-control'
  | 'completion-disputes'
  | 'repairs-management';

export type PropertyToolStatus = 'live' | 'coming-soon';

export type PropertyTool = {
  slug: string;
  title: string;
  shortTitle?: string;
  tagline: string;
  description: string;
  solves: string;
  audience: string;
  category: PropertyToolCategory;
  status: PropertyToolStatus;
  href: string;
  /** Shown on the homepage tools grid */
  featured?: boolean;
  featuredOrder?: number;
};

export const PROPERTY_TOOL_CATEGORIES: {
  key: PropertyToolCategory;
  label: string;
  shortLabel: string;
  description: string;
}[] = [
  {
    key: 'before-buying',
    label: 'Before buying or starting',
    shortLabel: 'Before buying',
    description: 'Verify land, documents, approvals, and readiness before money moves.',
  },
  {
    key: 'hiring-budgeting',
    label: 'Hiring, quotations & budgeting',
    shortLabel: 'Hiring & budget',
    description: 'Compare quotes, spot red flags, and plan costs with clearer assumptions.',
  },
  {
    key: 'remote-control',
    label: 'Remote project control',
    shortLabel: 'Remote control',
    description: 'Track stages, evidence, materials, and decisions when you cannot be on site.',
  },
  {
    key: 'completion-disputes',
    label: 'Completion, defects & disputes',
    shortLabel: 'Completion',
    description: 'Close out work with punch lists, warranties, handovers, and clear records.',
  },
  {
    key: 'repairs-management',
    label: 'Repairs & property management',
    shortLabel: 'Repairs',
    description: 'Triage issues, track maintenance, and keep multi-property work organized.',
  },
];

export const PROPERTY_TOOLS: PropertyTool[] = [
  // Featured / priority tools
  {
    slug: 'price-checker',
    title: 'Price Checker',
    shortTitle: 'Price Checker',
    tagline: 'Directional Nigeria repair ranges you can compare.',
    description:
      'Check typical contractor price bands for common Nigeria repairs before you request quotes or release money.',
    solves: 'Opaque quotations and guesswork about what a fair repair should cost',
    audience: 'Homeowners, landlords, and diaspora owners starting a repair',
    category: 'hiring-budgeting',
    status: 'live',
    href: '/tools/price-checker',
    featured: true,
    featuredOrder: 1,
  },
  {
    slug: 'construction-scam-red-flag-checker',
    title: 'Construction Scam Red-Flag Checker',
    shortTitle: 'Scam Red-Flag Checker',
    tagline: 'Review a proposed arrangement for warning signs.',
    description:
      'Walk through payment terms, urgency pressure, and missing paperwork to surface obvious construction scam risks before you commit.',
    solves: 'Customers missing obvious risks in WhatsApp-only contractor arrangements',
    audience: 'Diaspora homeowners and first-time clients',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/construction-scam-red-flag-checker',
    featured: true,
    featuredOrder: 2,
  },
  {
    slug: 'contractor-quote-comparison',
    title: 'Contractor Quote Comparison Tool',
    shortTitle: 'Quote Comparison',
    tagline: 'Align competing quotations item by item.',
    description:
      'Line up contractor quotes in one view so different formats, missing line items, and uneven allowances become visible.',
    solves: 'Comparing quotes that use different formats and hide gaps',
    audience: 'Homeowners and quantity surveyors',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/contractor-quote-comparison',
    featured: true,
    featuredOrder: 3,
  },
  {
    slug: 'nigeria-building-cost-planner',
    title: 'Nigeria Building Cost Planner',
    shortTitle: 'Building Cost Planner',
    tagline: 'Stage-by-stage budget ranges with dated assumptions.',
    description:
      'Produce preliminary stage budgets for Nigeria projects so early planning is based on ranges and assumptions, not one vague lump sum.',
    solves: 'Early budgeting uncertainty before drawings and BOQs are complete',
    audience: 'Future builders and renovators',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/nigeria-building-cost-planner',
    featured: true,
    featuredOrder: 4,
  },
  {
    slug: 'property-repair-triage',
    title: 'Property Repair Triage Assistant',
    shortTitle: 'Repair Triage',
    tagline: 'Turn symptoms into urgency and the right trade.',
    description:
      'Answer structured symptom questions to understand likely urgency, trade needed, and next step before calling the wrong artisan.',
    solves: 'Users calling the wrong trade or underestimating urgency',
    audience: 'Homeowners, tenants, and landlords',
    category: 'repairs-management',
    status: 'coming-soon',
    href: '/tools/property-repair-triage',
    featured: true,
    featuredOrder: 5,
  },
  {
    slug: 'land-purchase-risk-checker',
    title: 'Land Purchase Risk Checker',
    shortTitle: 'Land Risk Checker',
    tagline: 'Structured questions that generate a land risk report.',
    description:
      'Ask the right ownership, survey, and approval questions before buying land — especially useful for diaspora and first-time investors.',
    solves: 'Blind land purchases without a clear risk checklist',
    audience: 'Diaspora buyers and first-time investors',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/land-purchase-risk-checker',
    featured: true,
    featuredOrder: 6,
  },

  // A. Before buying or starting a project
  {
    slug: 'property-document-checklist',
    title: 'Property Document Checklist Generator',
    tagline: 'Location-specific document checklists.',
    description: 'Produces a location-specific document checklist so buyers know what to request.',
    solves: 'Uncertainty about what documents to request',
    audience: 'Buyers, lawyers, and agents',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/property-document-checklist',
  },
  {
    slug: 'survey-plan-review-request',
    title: 'Survey Plan Review Request Tool',
    tagline: 'Upload a plan for registered surveyor review.',
    description: 'Upload a survey plan and route it to a registered surveyor for coordinate and legitimacy checks.',
    solves: 'Confusion about coordinates and plan legitimacy',
    audience: 'Land buyers',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/survey-plan-review-request',
  },
  {
    slug: 'building-approval-navigator',
    title: 'Building Approval Navigator',
    tagline: 'Likely documents and steps by state and project type.',
    description: 'Shows likely approval documents and steps by Nigerian state and project type.',
    solves: 'Approval process confusion',
    audience: 'Homeowners and architects',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/building-approval-navigator',
  },
  {
    slug: 'pre-purchase-property-inspection',
    title: 'Pre-Purchase Property Inspection App',
    tagline: 'Guided structure, roofing, plumbing, and electrical checks.',
    description: 'Guides an inspector through structure, roofing, plumbing, and electrical checks before purchase.',
    solves: 'Hidden-defect risk at purchase',
    audience: 'Buyers and investors',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/pre-purchase-property-inspection',
  },
  {
    slug: 'property-document-vault',
    title: 'Property Document Vault',
    tagline: 'Titles, drawings, receipts, and agreements in one place.',
    description: 'Stores titles, drawings, receipts, inspections, and agreements for property owners and families.',
    solves: 'Missing and scattered paperwork',
    audience: 'Property owners and families',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/property-document-vault',
  },
  {
    slug: 'project-readiness-score',
    title: 'Project Readiness Score',
    tagline: 'Score land, drawings, budget, approvals, and team.',
    description: 'Scores land, drawings, budget, approvals, and professional team before you start building.',
    solves: 'Starting before preparations are complete',
    audience: 'First-time builders',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/project-readiness-score',
  },
  {
    slug: 'build-buy-or-renovate-calculator',
    title: 'Build, Buy or Renovate Calculator',
    tagline: 'Compare routes using budget, timeline, and use.',
    description: 'Compares build, buy, and renovate routes using budget, timeline, and intended use.',
    solves: 'Emotional decision-making without a structured comparison',
    audience: 'Diaspora investors',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/build-buy-or-renovate-calculator',
  },
  {
    slug: 'plot-to-project-feasibility',
    title: 'Plot-to-Project Feasibility Brief',
    tagline: 'What is realistically buildable on your plot.',
    description: 'Collects plot size, location, access, slope, and intended building into a feasibility brief.',
    solves: 'Uncertainty about what is realistically buildable',
    audience: 'Landowners',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/plot-to-project-feasibility',
  },
  {
    slug: 'abandoned-building-recovery-checker',
    title: 'Abandoned Building Recovery Checker',
    tagline: 'Photos and stage → recommended next steps.',
    description: 'Collects photos and current stage to recommend inspection categories and next steps for incomplete buildings.',
    solves: 'Confusion about restarting abandoned projects',
    audience: 'Owners of incomplete buildings',
    category: 'before-buying',
    status: 'coming-soon',
    href: '/tools/abandoned-building-recovery-checker',
  },

  // B. Hiring, quotations and budgeting
  {
    slug: 'contractor-verification-passport',
    title: 'Contractor Verification Passport',
    tagline: 'Checked identity, company, portfolio, and interview status.',
    description: 'Displays checked identity, company, portfolio, and interview status for a contractor.',
    solves: 'Uncertainty about who the contractor really is',
    audience: 'Homeowners',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/contractor-verification-passport',
  },
  {
    slug: 'contractor-interview-scorecard',
    title: 'Contractor Interview Scorecard',
    tagline: 'Consistent questions and graded answers.',
    description: 'Generates interview questions and grades answers consistently across candidates.',
    solves: 'Hiring based only on confidence or referrals',
    audience: 'Homeowners and consultants',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/contractor-interview-scorecard',
  },
  {
    slug: 'reference-check-manager',
    title: 'Reference Check Manager',
    tagline: 'Structured feedback from past clients.',
    description: 'Contacts past clients and records structured feedback against portfolio claims.',
    solves: 'Unverifiable portfolio claims',
    audience: 'Homeowners and BMH operations',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/reference-check-manager',
  },
  {
    slug: 'scope-of-work-generator',
    title: 'Scope of Work Generator',
    tagline: 'Photos and plain language → draft scope.',
    description: 'Turns photos and plain-language complaints into a draft scope for professional review.',
    solves: 'Vague verbal agreements',
    audience: 'Homeowners and artisans',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/scope-of-work-generator',
  },
  {
    slug: 'boq-in-plain-english',
    title: 'BOQ in Plain English',
    tagline: 'Understandable explanations without changing quantities.',
    description: 'Converts BOQ items into understandable explanations without changing quantities.',
    solves: 'Homeowners signing documents they cannot interpret',
    audience: 'Non-technical owners',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/boq-in-plain-english',
  },
  {
    slug: 'labour-versus-materials-analyser',
    title: 'Labour-versus-Materials Analyser',
    tagline: 'Separate labour, materials, transport, and fees.',
    description: 'Separates labour, materials, transport, and professional fees inside opaque lump-sum quotations.',
    solves: 'Opaque lump-sum quotations',
    audience: 'Homeowners',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/labour-versus-materials-analyser',
  },
  {
    slug: 'budget-contingency-calculator',
    title: 'Budget Contingency Calculator',
    tagline: 'Suggest a planning reserve for uncertainty.',
    description: 'Suggests a planning reserve based on project complexity and uncertainty.',
    solves: 'Spending the entire budget before variations arise',
    audience: 'Renovators and builders',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/budget-contingency-calculator',
  },
  {
    slug: 'material-price-watchlist',
    title: 'Material Price Watchlist',
    tagline: 'Track cement, steel, blocks, roofing, and finishes.',
    description: 'Tracks selected cement, steel, blocks, roofing, and finishing prices over time.',
    solves: 'Unexplained “prices have increased” claims',
    audience: 'Homeowners and QS professionals',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/material-price-watchlist',
  },
  {
    slug: 'quotation-fairness-review',
    title: 'Quotation Fairness Review Request',
    tagline: 'Independent professional review of a quote.',
    description: 'Lets users request an independent professional review of whether a quote is inflated or incomplete.',
    solves: 'Not knowing whether a quote is inflated or incomplete',
    audience: 'Property owners',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/quotation-fairness-review',
  },
  {
    slug: 'professional-role-finder',
    title: 'Professional Role Finder',
    tagline: 'Architect, engineer, QS, surveyor, or artisan?',
    description: 'Explains whether a project needs an architect, engineer, QS, surveyor, or artisan.',
    solves: 'Hiring the wrong professional',
    audience: 'First-time homeowners',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/professional-role-finder',
  },
  {
    slug: 'project-payment-plan-builder',
    title: 'Project Payment Plan Builder',
    tagline: 'Deposits, stage payments, and retention.',
    description: 'Converts scope into proposed deposits, stage payments, and retention for professional approval.',
    solves: 'Uncontrolled upfront payment',
    audience: 'Clients and contractors',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/project-payment-plan-builder',
  },
  {
    slug: 'contract-builder-small-repairs',
    title: 'Contract Builder for Small Repairs',
    tagline: 'Simple scope, timeline, payment, and evidence agreement.',
    description: 'Generates a simple scope, timeline, payment, and evidence agreement for small repairs.',
    solves: 'Artisans beginning work through WhatsApp promises alone',
    audience: 'Repair customers',
    category: 'hiring-budgeting',
    status: 'coming-soon',
    href: '/tools/contract-builder-small-repairs',
  },

  // C. Remote project control and evidence
  {
    slug: 'remote-site-progress-tracker',
    title: 'Remote Site Progress Tracker',
    tagline: 'Stages, percentage status, and evidence.',
    description: 'Shows project stages, percentage status, and evidence so owners are not dependent on verbal reports.',
    solves: 'Owners depending on verbal progress reports',
    audience: 'Diaspora and busy local homeowners',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/remote-site-progress-tracker',
  },
  {
    slug: 'timestamped-site-evidence-camera',
    title: 'Timestamped Site Evidence Camera',
    tagline: 'Date, time, project, and optional location metadata.',
    description: 'Captures date, time, project, and optional location metadata with site photos.',
    solves: 'Recycled or contextless site photos',
    audience: 'Contractors and inspectors',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/timestamped-site-evidence-camera',
  },
  {
    slug: 'weekly-diaspora-project-digest',
    title: 'Weekly Diaspora Project Digest',
    tagline: 'Completed work, spending, delays, and next steps.',
    description: 'Automatically summarises completed work, spending, delays, and next steps each week.',
    solves: 'Owners searching through chats for updates',
    audience: 'Nigerians abroad',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/weekly-diaspora-project-digest',
  },
  {
    slug: 'daily-site-diary',
    title: 'Daily Site Diary',
    tagline: 'Workers, weather, tasks, deliveries, and incidents.',
    description: 'Records workers, weather, tasks, deliveries, and incidents for historical site records.',
    solves: 'Missing historical site records',
    audience: 'Contractors and project managers',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/daily-site-diary',
  },
  {
    slug: 'contractor-attendance-tracker',
    title: 'Contractor Attendance Tracker',
    tagline: 'Planned versus actual site attendance.',
    description: 'Records planned versus actual site attendance to expose no-shows and inactivity.',
    solves: 'Repeated no-shows and unexplained inactivity',
    audience: 'Homeowners and supervisors',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/contractor-attendance-tracker',
  },
  {
    slug: 'project-delay-alert-system',
    title: 'Project Delay Alert System',
    tagline: 'Flag overdue tasks with recovery dates.',
    description: 'Flags overdue tasks and requests a documented reason and recovery date.',
    solves: 'Delays becoming visible too late',
    audience: 'All project parties',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/project-delay-alert-system',
  },
  {
    slug: 'materials-delivery-verifier',
    title: 'Materials Delivery Verifier',
    tagline: 'Match notes, photos, and quantities to orders.',
    description: 'Matches delivery notes, photos, and quantities against approved orders.',
    solves: 'Substituted or incomplete deliveries',
    audience: 'Homeowners and site managers',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/materials-delivery-verifier',
  },
  {
    slug: 'material-usage-reconciliation',
    title: 'Material Usage Reconciliation Tool',
    tagline: 'Purchased, used, remaining, and wasted materials.',
    description: 'Compares purchased, used, remaining, and wasted materials on a project.',
    solves: 'Diversion and unexplained shortages',
    audience: 'QS professionals and owners',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/material-usage-reconciliation',
  },
  {
    slug: 'site-inventory-register',
    title: 'Site Inventory Register',
    tagline: 'Tools, materials, and equipment on and off site.',
    description: 'Tracks tools, materials, and equipment entering and leaving site.',
    solves: 'Loss and unrecorded movement',
    audience: 'Contractors and homeowners',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/site-inventory-register',
  },
  {
    slug: 'receipt-and-invoice-vault',
    title: 'Receipt and Invoice Vault',
    tagline: 'Organise receipts by stage and supplier.',
    description: 'Organises receipts by project stage and supplier instead of scattered WhatsApp files.',
    solves: 'Financial evidence getting lost in WhatsApp',
    audience: 'Owners and accountants',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/receipt-and-invoice-vault',
  },
  {
    slug: 'change-order-approval',
    title: 'Change-Order Approval App',
    tagline: 'Approve extras before work begins.',
    description: 'Requires scope, reason, cost, impact, and owner approval before extra work begins.',
    solves: 'Surprise invoices and disputed variations',
    audience: 'Clients and contractors',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/change-order-approval',
  },
  {
    slug: 'project-decision-log',
    title: 'Project Decision Log',
    tagline: 'Who approved each material, design, or scope decision.',
    description: 'Records who approved each material, design, or scope decision.',
    solves: 'Later arguments over instructions',
    audience: 'Architects, homeowners, and contractors',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/project-decision-log',
  },
  {
    slug: 'photo-to-milestone-matcher',
    title: 'Photo-to-Milestone Matcher',
    tagline: 'Attach evidence to a specific deliverable.',
    description: 'Requires evidence to be attached to a specific deliverable before it counts as progress.',
    solves: 'Random photos being presented as proof of progress',
    audience: 'Remote homeowners',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/photo-to-milestone-matcher',
  },
  {
    slug: 'remote-site-visit-report-builder',
    title: 'Remote Site Visit Report Builder',
    tagline: 'Consistent findings, media, and actions.',
    description: 'Lets consultants generate consistent reports with findings, media, and actions.',
    solves: 'Unstructured inspection updates',
    audience: 'Architects, engineers, and QS professionals',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/remote-site-visit-report-builder',
  },
  {
    slug: 'independent-stage-verification',
    title: 'Independent Stage Verification Booking',
    tagline: 'Request an unrelated professional before payment.',
    description: 'Allows owners to request an unrelated professional before releasing stage payment.',
    solves: 'Relying entirely on the contractor’s own progress claims',
    audience: 'Diaspora clients',
    category: 'remote-control',
    status: 'coming-soon',
    href: '/tools/independent-stage-verification',
  },

  // D. Completion, defects and disputes
  {
    slug: 'digital-snagging-punch-list',
    title: 'Digital Snagging and Punch-List App',
    tagline: 'Defects with photos, responsibility, and deadline.',
    description: 'Records defects with photos, responsibility, and deadline so punch lists are not forgotten.',
    solves: 'Verbal defect lists that are forgotten',
    audience: 'Homeowners and inspectors',
    category: 'completion-disputes',
    status: 'coming-soon',
    href: '/tools/digital-snagging-punch-list',
  },
  {
    slug: 'completion-acceptance-checklist',
    title: 'Completion Acceptance Checklist',
    tagline: 'What must be inspected before “satisfied”.',
    description: 'Defines what must be inspected before final satisfaction is recorded.',
    solves: 'Premature final approval',
    audience: 'Clients and contractors',
    category: 'completion-disputes',
    status: 'coming-soon',
    href: '/tools/completion-acceptance-checklist',
  },
  {
    slug: 'final-account-reconciliation',
    title: 'Final Account Reconciliation Tool',
    tagline: 'Original quote, changes, payments, and balance.',
    description: 'Compares original quote, approved changes, payments, and remaining balance.',
    solves: 'Disputes about the final amount',
    audience: 'Homeowners and QS professionals',
    category: 'completion-disputes',
    status: 'coming-soon',
    href: '/tools/final-account-reconciliation',
  },
  {
    slug: 'contractor-performance-report',
    title: 'Contractor Performance Report',
    tagline: 'Score communication, timeliness, quality, and resolution.',
    description: 'Scores communication, timeliness, quality, evidence, and issue resolution.',
    solves: 'Reviews based only on emotion',
    audience: 'Future clients and BMH',
    category: 'completion-disputes',
    status: 'coming-soon',
    href: '/tools/contractor-performance-report',
  },
  {
    slug: 'warranty-and-callback-tracker',
    title: 'Warranty and Callback Tracker',
    tagline: 'Warranty periods and repair obligations.',
    description: 'Stores warranty periods and repair obligations after handover.',
    solves: 'Contractors disappearing after handover',
    audience: 'Homeowners and property managers',
    category: 'completion-disputes',
    status: 'coming-soon',
    href: '/tools/warranty-and-callback-tracker',
  },
  {
    slug: 'dispute-timeline-builder',
    title: 'Dispute Timeline Builder',
    tagline: 'Contracts, payments, messages, and evidence in order.',
    description: 'Organises contracts, payments, messages, changes, and evidence chronologically.',
    solves: 'Inability to explain what happened in a dispute',
    audience: 'Clients, mediators, and lawyers',
    category: 'completion-disputes',
    status: 'coming-soon',
    href: '/tools/dispute-timeline-builder',
  },
  {
    slug: 'project-handover-pack',
    title: 'Project Handover Pack Generator',
    tagline: 'One downloadable pack for drawings, warranties, and receipts.',
    description:
      'Produces one downloadable file containing drawings, warranties, receipts, contractors, and maintenance instructions.',
    solves: 'Incomplete handovers',
    audience: 'Property owners',
    category: 'completion-disputes',
    status: 'coming-soon',
    href: '/tools/project-handover-pack',
  },

  // E. Repairs and ongoing property management
  {
    slug: 'tenant-maintenance-request-portal',
    title: 'Tenant Maintenance Request Portal',
    tagline: 'Photos, access details, and urgency from tenants.',
    description: 'Lets tenants submit problems with photos, access details, and urgency.',
    solves: 'Requests disappearing inside calls and chats',
    audience: 'Landlords and property managers',
    category: 'repairs-management',
    status: 'coming-soon',
    href: '/tools/tenant-maintenance-request-portal',
  },
  {
    slug: 'multi-property-maintenance-dashboard',
    title: 'Multi-Property Maintenance Dashboard',
    tagline: 'Open repairs, spending, warranties, and recurring issues.',
    description: 'Tracks open repairs, spending, warranties, and recurring problems across properties.',
    solves: 'Owners losing control as their portfolio grows',
    audience: 'Landlords, schools, churches, short-let operators, and diaspora investors',
    category: 'repairs-management',
    status: 'coming-soon',
    href: '/tools/multi-property-maintenance-dashboard',
  },
];

export const FEATURED_PROPERTY_TOOLS = PROPERTY_TOOLS.filter((tool) => tool.featured).sort(
  (a, b) => (a.featuredOrder ?? 99) - (b.featuredOrder ?? 99),
);

export function getPropertyToolBySlug(slug: string): PropertyTool | undefined {
  return PROPERTY_TOOLS.find((tool) => tool.slug === slug);
}

export function getPropertyToolsByCategory(category: PropertyToolCategory): PropertyTool[] {
  return PROPERTY_TOOLS.filter((tool) => tool.category === category);
}
